### ISSUE TITLE
Light button slow to turn off and on lights, when printing. 

### ISSUE THREAD

**Issue by Mike3987** [QIDITECH/QIDI_SMART3#23]
When the printer is printing, I click the light button on the display and there is a couple second delay before turning on and off the lights. 

In the Fluidd interface, turning on and off the light has the same delay. 

When I'm not printing, there is no delay.

**Comment by CChen616** [comment]
The function to switch the light on and off is implemented through a Gcode macro. 

When not printing, the Gcode queue is empty, so it will execute immediately. 

During printing, it needs to wait until the current executing Gcode is completed before execution. 

Thank you for pointing this out, but since it is not a primary feature and has minimal impact on printing, we will maintain this feature for the time being.
